package ir.part.sdk.ara.base.di

enum class ComponentsKey {
    Ara,
    BASE,
    DATA,
    COMMON_UI,
    DOMAIN_FILE,
    DOMAIN_USER_MANAGER,
    DOMAIN_TASK,
    DOMAIN_MENU,
    DOMAIN_HOME,
    DOMAIN_PAYMENT,
    DATA_DASHBOARD,
    DATA_BARJAVAND,
    DATA_PAYMENT,
    DATA_USER_MANAGER,
    DATA_STATE,
    UI_DOCUMENT,
    UI_MENU,
    UI_MENU_COMMENT,
    UI_MENU_RAHYAR,
    UI_USER,
    UI_SHARED_FEATURE,
    UI_HOME
}